# Generated by Django 5.0.6 on 2024-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
